##########################
# 1) TEMPLATE & ILM
##########################

# Charge un template Elasticsearch adapté à ton index custom
setup.template:
  name: "app-logs"          # nom du template
  pattern: "app-logs-*"     # pattern de tes indices
  enabled: true             # active le chargement du template

# Désactive l'Index Lifecycle Management pour forcer l'utilisation de l'index ci‑dessous
setup.ilm.enabled: false

##########################
# 2) COLLECTION DES LOGS
##########################

filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /app/backend/backend.log   # chemin interne dans le conteneur
    multiline.pattern: '^\s'
    multiline.negate: false
    multiline.match: after

##########################
# 3) ENVOI VERS ELASTICSEARCH
##########################

output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  index: "app-logs-%{+yyyy.MM.dd}"