apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
data:
  # This is a placeholder. In a real environment, you would replace this with your actual API key
  # The value should be base64 encoded: echo -n "your-api-key" | base64
  openai-api-key: UkVQTEFDRV9XSVRIX1lPVVJfQVBJX0tFWQ==