apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - app-secrets.yaml
  - backend-deployment.yaml
  - frontend-deployment.yaml
  - backend-service.yaml
  - frontend-service.yaml